/******************************************************************************
* File Name:   print_functions.c
*
* Description: This source file contains the necessary APIs to configure a USIC
* block as UART for debug messages. It uses the default UART pins available on 
* the kits.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2021, Infineon Technologies AG
* All rights reserved.
*
* Boost Software License - Version 1.0 - August 17th, 2003
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*
*****************************************************************************/
#include "cybsp.h"
#include "print_functions.h"

/*****************************************************************************
 * LOCAL FUNCTION PROTOTYPES
 ****************************************************************************/
static uint8_t hex_to_ascii(uint8_t data);
static void print_byte(uint8_t data);

/*******************************************************************************
* Function Name: print_buffer
********************************************************************************
* Summary:
* This function prints a buffer in hexadecimal format.
*
* Parameters:
* buf - pointer to the buffer to print
* len - length of the buffer
*
* Return:
* void
*
*******************************************************************************/
void print_buffer_hex(uint8_t *buf, uint32_t len)
{
    uint32_t i;
    XMC_USIC_CH_TXFIFO_Flush(CYBSP_DEBUG_UART_HW);


    for(i = 0 ; i < len; i++)
    {
        print_byte(buf[i]);
    }
    XMC_UART_CH_Transmit(CYBSP_DEBUG_UART_HW, (uint16_t)'\r');
    while((XMC_UART_CH_GetStatusFlag(CYBSP_DEBUG_UART_HW) & XMC_UART_CH_STATUS_FLAG_TRANSFER_STATUS_BUSY));
    XMC_UART_CH_Transmit(CYBSP_DEBUG_UART_HW, (uint16_t)'\n');
    while((XMC_UART_CH_GetStatusFlag(CYBSP_DEBUG_UART_HW) & XMC_UART_CH_STATUS_FLAG_TRANSFER_STATUS_BUSY));
}

/*******************************************************************************
* Function Name: print_buffer_text
********************************************************************************
* Summary:
* This function prints a buffer in ascii format.
*
* Parameters:
* buf - pointer to the buffer to print
* len - length of the buffer
*
* Return:
* void
*
*******************************************************************************/
void print_buffer_text(uint8_t *buf, uint32_t len)
{
    uint32_t i;
    XMC_USIC_CH_TXFIFO_Flush(CYBSP_DEBUG_UART_HW);

    for(i = 0 ; i < len; i++)
    {
        XMC_UART_CH_Transmit(CYBSP_DEBUG_UART_HW, (uint16_t)buf[i]);
        while((XMC_UART_CH_GetStatusFlag(CYBSP_DEBUG_UART_HW) & XMC_UART_CH_STATUS_FLAG_TRANSFER_STATUS_BUSY));
    }
}

/*******************************************************************************
* Function Name: print_byte
********************************************************************************
* Summary:
* This function prints a buffer in hexadecimal format.
*
* Parameters:
* data - data byte to print
*
* Return:
* void
*
*******************************************************************************/
static void print_byte(uint8_t data)
{
    uint8_t tempVar;

    XMC_UART_CH_Transmit(CYBSP_DEBUG_UART_HW, (uint16_t)'0');
    while((XMC_UART_CH_GetStatusFlag(CYBSP_DEBUG_UART_HW) & XMC_UART_CH_STATUS_FLAG_TRANSFER_STATUS_BUSY));
    XMC_UART_CH_Transmit(CYBSP_DEBUG_UART_HW, (uint16_t)'x');
    while((XMC_UART_CH_GetStatusFlag(CYBSP_DEBUG_UART_HW) & XMC_UART_CH_STATUS_FLAG_TRANSFER_STATUS_BUSY));

    /* Print upper nibble first */
    tempVar = (data & 0xF0) >> 4;
    XMC_UART_CH_Transmit(CYBSP_DEBUG_UART_HW, (uint16_t)hex_to_ascii(tempVar));
    while((XMC_UART_CH_GetStatusFlag(CYBSP_DEBUG_UART_HW) & XMC_UART_CH_STATUS_FLAG_TRANSFER_STATUS_BUSY));

    tempVar = (data & 0x0F);
    XMC_UART_CH_Transmit(CYBSP_DEBUG_UART_HW, (uint16_t)hex_to_ascii(tempVar));
    while((XMC_UART_CH_GetStatusFlag(CYBSP_DEBUG_UART_HW) & XMC_UART_CH_STATUS_FLAG_TRANSFER_STATUS_BUSY));

    XMC_UART_CH_Transmit(CYBSP_DEBUG_UART_HW, (uint16_t)' ');
    while((XMC_UART_CH_GetStatusFlag(CYBSP_DEBUG_UART_HW) & XMC_UART_CH_STATUS_FLAG_TRANSFER_STATUS_BUSY));
}

/*******************************************************************************
* Function Name: hex_to_ascii
********************************************************************************
* Summary:
* This function converts a byte into ascii format.
*
* Parameters:
* data - data byte to convert to ascii
*
* Return:
* void
*
*******************************************************************************/
static uint8_t hex_to_ascii(uint8_t data)
{
    if(data < 10)
    {
        return (data + 48);
    }
    else
    {
        return (data + 55);
    }
}
/*CODE_BLOCK_END*/