/******************************************************************************
* File Name:   xmc4_e_eeprom_example.c
*
* Description: This Source file implements the example application to use 
* APIs in e_eeprom_xmc1.c file function for XMC4000 MCU. 
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2021, Infineon Technologies AG
* All rights reserved.                        
*                                             
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*                                                                              
*****************************************************************************/
//#ifdef TARGET_KIT_XMC47_RELAX_V1

#include "xmc_device.h"
#if (UC_FAMILY == XMC4)
#include <stdio.h>
#include "xmc4_e_eeprom.h"
#include "xmc4_e_eeprom_example.h"
#include "print_functions.h"

/*****************************************************************************
 * Defines
 ****************************************************************************/
#define E_EEPROM_SIZE            64U    /* Size of the EEPROM */
/* Macros for the messages to print */
#define E_EEPROM_EXISTING_DATA_STRING    "Existing Data in EEPROM\r\n"
#define E_EEPROM_NEW_DATA_STRING        "New Data in EEPROM\r\n"

/*****************************************************************************
 * Gobal variables
 ****************************************************************************/
E_EEPROM_XMC4_t e_eeprom;     /* Emulated EEPROM handle */

/*****************************************************************************
 * Local function prototypes
 ****************************************************************************/
static void prep_write_buffer(uint8_t *rbuf, uint8_t *wbuf, uint32_t len);

/*******************************************************************************
* Function Name: prep_write_buffer
********************************************************************************
* Summary:
* This function increments each element of read buffer and stores the new value
* in write buffer. It is done for testing.
*
* Parameters:
* rbuf - read buffer
* wbuf - write buffer
* len - lenght of buffers
*
* Return:
* void
*
*******************************************************************************/
static void prep_write_buffer(uint8_t *rbuf, uint8_t *wbuf, uint32_t len)
{
    uint32_t i;
    for(i = 0; i < len; i++)
    {
        wbuf[i] = rbuf[i] + 1;
    }
}

/*******************************************************************************
* Function Name: E_EEPROM_example
********************************************************************************
* Summary:
* Function to initialize eeprom and execute the tests. After initialization, 
* It performs below steps.
* 1 - Read data from an eeprom block
* 2 - increment the read data by 1 and program it back to eeprom
* 3 - Read and print new data from eeprom
*
* Parameters:
* void
*
* Return:
* void
*
*******************************************************************************/
void E_EEPROM_example()
{
    uint8_t data_wbuffer[E_EEPROM_SIZE];
    uint8_t data_rbuffer[E_EEPROM_SIZE];

    /* Initialize emulated EEPROM */
    E_EEPROM_XMC4_Init(&e_eeprom, E_EEPROM_SIZE);

    /* Read and print existing data from EEPROM block */
    E_EEPROM_XMC4_ReadArray(0, (uint8_t *const)data_rbuffer, E_EEPROM_SIZE);
    print_buffer_text((uint8_t *)E_EEPROM_EXISTING_DATA_STRING, sizeof(E_EEPROM_EXISTING_DATA_STRING));
    print_buffer_hex(data_rbuffer, E_EEPROM_SIZE);

    /* Fill write buffer and write new data to EEPROM */
    prep_write_buffer(data_rbuffer, data_wbuffer, E_EEPROM_SIZE);
    E_EEPROM_XMC4_WriteArray(0, (uint8_t *const)data_wbuffer, E_EEPROM_SIZE);
    E_EEPROM_XMC4_UpdateFlashContents();

    /* Read and print new data from EEPROM to verify */
    E_EEPROM_XMC4_ReadArray(0, (uint8_t *const)data_rbuffer, E_EEPROM_SIZE);
    print_buffer_text((uint8_t *)E_EEPROM_NEW_DATA_STRING, sizeof(E_EEPROM_NEW_DATA_STRING));
    print_buffer_hex(data_rbuffer, E_EEPROM_SIZE);
}
#endif

